# NOT TO DO LIST API

@baseUrl =http://localhost:8000/api/v1/tasks


### GET

GET {{baseUrl}}

### POST

POST {{baseUrl}}
Content-Type: application/json

{

"task":"Dreagasd",

"hr":10,
"type":"bad"

}

### UPDATE
PATCH  {{baseUrl}}
Content-Type: application/json

{
"_id":"66b43962737ce139d7d7b585",
"type":"bad"
}


### DELETE

DELETE  {{baseUrl}}/66b43962737ce139d7d7b585


