# NOT TO DO LIST API

@baseUrl =http://localhost:8000/api/v1/tasks


### GET
GET {{baseUrl}}

### POST

POST {{baseUrl}}
Content-Type: application/json

{
"task":"cooking",
"hr":10
}

### UPDATE
PUT {{baseUrl}}


### DELETE

DELETE  {{baseUrl}}

