# NOT TO DO LIST API

@baseUrl =http://localhost:8000/api/v1/tasks


### GET

GET {{baseUrl}}

### POST

POST {{baseUrl}}
Content-Type: application/json

{

"task":"Dreaming",
"hr":40,
"type":"entry"
}

### UPDATE
PATCH  {{baseUrl}}
Content-Type: application/json

{
"_id":"66b4317c485062439e2146dc",
"type":"bad"
}


### DELETE

DELETE  {{baseUrl}}/66b4317c485062439e2146dc


